# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3df6fdf33ac993ff8ff413ef94e47b80bd41fe9a8d3eced574c50f3cc15973ae2a49fc792ec130fe72479551a43280a5a02ec66ac9eb7158523095a4bb3e936

test:
  secret_key_base: 6d567625f4f6d99fe09c8299c0e6d6aadbe428d39146cf1e54703a857d930fcb60c113cd90ded5bb8a68101a1c352d6d6200d83d95ca65501a1564d1d594c675

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
